### ISSUE TITLE
roadmap: Adding hardware usage and thermal stats as quality check for CICD

### ISSUE THREAD

**Issue by TC117** [janhq/jan#4513]
### Goal

- Adding performance test for Jan to make sure, Jan not causing unexpecting CPU/GPU thermal issue

Ramon: Thoughts regarding heating (please note that I haven't gone through all of our codebase yet and it is possible that part of my suggestions have been implemented already):

We could implement an intelligent thermal management & CI/CD testing strategy
For example, in CI/CD we could update our [test suite](https://github.com/janhq/jan/blob/dev/.github/workflows/jan-electron-linter-and-test.yml) and include something along the lines of:
```
jobs:
  performance-matrix:
    strategy:
      matrix:
        include:
          - os: [ubuntu, windows, macos]
          - gpu: [nvidia, apple-silicon]
          - ram: [8GB, 16GB, 32GB]
# then
    steps:
      - uses: actions/checkout@v3
      - name: Performance Stress Test
        run: |
          python -m pytest tests/performance \
            --gpu ${{ matrix.gpu }} \
            --ram ${{ matrix.ram }} \
            --thermal-threshold 80

```
Within the Python Engine we could implement smart model loading logic. There is also the package [gpustat](https://github.com/wookayin/gpustat) that could be helpful
```
class ThermalGuard:
    def load_model(self):
        if system_temp > MAX_THRESHOLD:
            return low_precision_model()
        elif system_temp > EMERGENCY_THRESHOLD:
            trigger_cooldown()
        return full_precision_model()
```
