### ISSUE TITLE
enhancement: performance test CI workflow to minimize abrupt memory consumption

### ISSUE THREAD

**Issue by ramonpzg** [janhq/jan#4606]
Users have reported increased memory usage with models that previously would not present such a spike. Suggestions from the discord thread on this:

Thoughts regarding heating (please note that I haven't gone through all of our codebase yet and it is possible that part of my suggestions have been implemented already):

We could implement an intelligent thermal management & CI/CD testing strategy
- For example, in CI/CD we could update our [test suite](https://github.com/janhq/jan/blob/dev/.github/workflows/jan-electron-linter-and-test.yml) and include something along the lines of:
```yaml
jobs:
  performance-matrix:
    strategy:
      matrix:
        include:
          - os: [ubuntu, windows, macos]
          - gpu: [nvidia, apple-silicon]
          - ram: [8GB, 16GB, 32GB]
# then
    steps:
      - uses: actions/checkout@v3
      - name: Performance Stress Test
        run: |
          python -m pytest tests/performance \
            --gpu ${{ matrix.gpu }} \
            --ram ${{ matrix.ram }} \
            --thermal-threshold 80
```
- Within the Python Engine we could implement smart model loading logic. There is also the package [`gpustat`](https://github.com/wookayin/gpustat) that could be helpful
```python
class ThermalGuard:
    def load_model(self):
        if system_temp > MAX_THRESHOLD:
            return low_precision_model()
        elif system_temp > EMERGENCY_THRESHOLD:
            trigger_cooldown()
        return full_precision_model()
```

- Would users be interested in a straightforward Performance Dashboard or would this be something we could offer as a paid offering where user have a "one-click" option to send Jan analytics to an external dashboard and get startistics regarding conversations, topics, memory usage, heating, and so on? :thinking:  Weights & Biases have implemented this mode of data sharing incredibly well and could serve as an example on how to go about this
```typescript
const PerformanceMonitor = () => {
  const adjustPerformance = (temp) => {
    if (temp > 75) return 'LOW_POWER';
    if (temp > 85) return 'EMERGENCY_STOP';
    return 'OPTIMAL';
  };
};
```

In essence, we could
- Include adaptive precision loading
- have consent-based telemetry
- provide user-configurable performance modes
- tweak error handling
